//! The `authenticate` tool: an alternative, reverse authorization path for MCP
//! clients whose OAuth 2.1 implementation is broken or that run on devices
//! where a browser cannot be launched.
//!
//! Normal flow (unchanged): the client performs the RFC 9728 / OAuth 2.1
//! client-driven flow and sends a `Bearer` token on every request.
//!
//! Reverse flow (this module): the user visits
//! <https://open.longbridge.com/connect>, generates a short-lived, one-time
//! OAuth **authorization code**, and pastes it to the AI. The AI calls
//! `authenticate` with that code; the server exchanges it for tokens at the
//! Longbridge token endpoint and returns the resulting access token to the
//! client so it can be used as the `Bearer` credential on subsequent calls.
//!
//! ## Architectural note (session binding)
//!
//! This server is **stateless** (see `docs/architecture.md`): it uses
//! `NeverSessionManager` with `stateful_mode = false`, so there is no
//! server-side session store and no server->client push channel. The only
//! durable "session" is the `Authorization: Bearer` header the client attaches
//! to each request. Consequently `authenticate` cannot silently mutate hidden
//! server state; instead it returns the freshly minted access token in its
//! response and instructs the client to send it as the Bearer token going
//! forward. This keeps the credential model identical to the existing OAuth
//! path (the server never persists user credentials) while still giving
//! OAuth-incapable clients a working authorization route.

use std::time::Duration;

use rmcp::ErrorData as McpError;
use rmcp::model::CallToolResult;
use rmcp::schemars::JsonSchema;
use rmcp::serde::Deserialize;

use crate::tools::tool_result;

/// The page where a user generates a one-time authorization code to paste to
/// the AI. Referenced in the tool description and in error hints so the AI can
/// self-heal by directing the user here.
pub const CONNECT_PAGE_URL: &str = "https://open.longbridge.com/connect";

/// `/connect` page URL matching the deployment region: a `.cn` deployment
/// (detected via `LONGBRIDGE_HTTP_URL` pointing at openapi.longbridge.cn)
/// should send users to open.longbridge.cn instead of the global site.
pub fn connect_page_url() -> &'static str {
    if oauth_base_url().contains("longbridge.cn") {
        "https://open.longbridge.cn/connect"
    } else {
        CONNECT_PAGE_URL
    }
}

/// `redirect_uri` that the "AI Agent" OAuth client is registered with. The
/// authorization code minted on the connect page is bound to this exact URI, so
/// the token exchange must send the same value.
const AGENT_REDIRECT_URI: &str = "https://open.longbridge.com/connect/done";

/// OAuth `client_id` of the dedicated "AI Agent" public client used for the
/// authorization-code exchange. This is a public client: no client secret and
/// no PKCE (the code is short-lived and one-time).
///
/// Defaults to the production client; set `LONGBRIDGE_AGENT_CLIENT_ID` to
/// override for non-prod deployments (canary client:
/// `c0c3ae51-dd73-4706-8d29-601ae376034c` on openapi.longbridge.xyz),
/// mirroring how `LONGBRIDGE_HTTP_URL` redirects the exchange endpoint.
const AGENT_CLIENT_ID: &str = "c91cd252-2f89-4024-9c5d-7b1340fc3bd1";

/// Resolve the "AI Agent" client id, honoring `LONGBRIDGE_AGENT_CLIENT_ID`.
fn agent_client_id() -> String {
    std::env::var("LONGBRIDGE_AGENT_CLIENT_ID").unwrap_or_else(|_| AGENT_CLIENT_ID.to_string())
}

/// Parameters for the `authenticate` tool.
#[derive(Debug, Deserialize, JsonSchema)]
pub struct AuthenticateParam {
    /// One-time OAuth authorization code generated by the user at
    /// <https://open.longbridge.com/connect>. Valid for 5 minutes and usable
    /// only once.
    pub auth_code: String,
}

/// Successful OAuth token-endpoint response (standard OAuth 2.0 fields).
#[derive(Debug, Deserialize)]
struct TokenResponse {
    access_token: String,
    #[serde(default)]
    refresh_token: Option<String>,
    #[serde(default)]
    token_type: Option<String>,
    #[serde(default)]
    expires_in: Option<i64>,
    #[serde(default)]
    scope: Option<String>,
}

/// Error body returned by the OAuth token endpoint on failure (RFC 6749 5.2).
#[derive(Debug, Deserialize)]
struct TokenErrorResponse {
    #[serde(default)]
    error: Option<String>,
    #[serde(default)]
    error_description: Option<String>,
}

/// Base OAuth URL (no trailing slash), honoring `LONGBRIDGE_HTTP_URL` so tests
/// and non-prod deployments can redirect the exchange. Mirrors
/// `auth::metadata::longbridge_oauth_url`.
fn oauth_base_url() -> String {
    std::env::var("LONGBRIDGE_HTTP_URL")
        .unwrap_or_else(|_| "https://openapi.longbridge.com".to_string())
        .trim_end_matches('/')
        .to_string()
}

fn self_heal_hint() -> String {
    format!(
        "The authorization code is invalid or has expired. Generate a new one at {} and call `authenticate` again.",
        connect_page_url()
    )
}

/// Build the ordered exchange candidates for a user-pasted authorization
/// code. The connect page displays codes in a pure-alphanumeric base58 form
/// (raw standard-base64 codes get escaped or truncated by chat apps); legacy
/// pages used an unpadded base64url form. Candidate order: base58-decoded,
/// base64url-restored, the string as pasted. A rejected lookup does not
/// consume the one-time code, so later attempts are safe.
///
/// Mirrors the CLI's `auth login --auth-code` — keep the two in sync (both
/// repos pin the same shared test vector).
fn auth_code_candidates(input: &str) -> Vec<String> {
    use base64::Engine as _;
    let raw = input
        .trim()
        .trim_matches(|c| matches!(c, '"' | '\'' | '`'))
        .to_string();
    if raw.is_empty() {
        return Vec::new();
    }
    let mut candidates: Vec<String> = Vec::new();
    if let Ok(bytes) = bs58::decode(&raw).into_vec() {
        candidates.push(base64::engine::general_purpose::STANDARD.encode(bytes));
    }
    if let Ok(bytes) = base64::engine::general_purpose::URL_SAFE_NO_PAD.decode(&raw) {
        let restored = base64::engine::general_purpose::STANDARD.encode(bytes);
        if !candidates.contains(&restored) {
            candidates.push(restored);
        }
    }
    if !candidates.contains(&raw) {
        candidates.push(raw);
    }
    candidates
}

/// Exchange a one-time authorization code for tokens and report the result.
///
/// On success, returns a message containing the minted access token plus a
/// scope/account summary, and instructs the client to use the token as its
/// `Bearer` credential on subsequent requests.
pub async fn authenticate(
    already_authenticated: bool,
    param: AuthenticateParam,
) -> Result<CallToolResult, McpError> {
    if already_authenticated {
        return Ok(tool_result(
            serde_json::json!({
                "status": "already_authenticated",
                "message": "This session is already authenticated. No action needed - your existing credentials remain in effect. To switch accounts, reconnect with a different token.",
            })
            .to_string(),
        ));
    }

    let candidates = auth_code_candidates(&param.auth_code);
    if candidates.is_empty() {
        return Err(McpError::invalid_params(
            format!("`auth_code` must not be empty. {}", self_heal_hint()),
            None,
        ));
    }

    let mut token = None;
    // Prefer the first definitive rejection from the token endpoint over any
    // later transport error (e.g. the fallback attempt failing to connect).
    let mut first_rejection: Option<McpError> = None;
    let mut last_other: Option<McpError> = None;
    for candidate in &candidates {
        match exchange_code(candidate).await {
            Ok(t) => {
                token = Some(t);
                break;
            }
            Err(e) if e.code == rmcp::model::ErrorCode::INVALID_PARAMS => {
                if first_rejection.is_none() {
                    first_rejection = Some(e);
                }
            }
            Err(e) => last_other = Some(e),
        }
    }
    let Some(token) = token else {
        return Err(first_rejection
            .or(last_other)
            .expect("at least one candidate is attempted"));
    };

    let scopes: Vec<String> = token
        .scope
        .as_deref()
        .map(|s| s.split_whitespace().map(str::to_string).collect())
        .unwrap_or_default();

    let account_channel = crate::tools::decode_jwt_account_channel(&token.access_token)
        .unwrap_or_else(|| "lb".into());

    let next_steps = format!(
        "Authentication successful. The full tool set unlocks once requests carry this access token. \
         This server is stateless and does NOT store credentials, so the MCP client must attach \
         `Authorization: Bearer {token}` to every subsequent request. \
         If the client supports configuring request headers, set it there once — e.g. in Claude Code: \
         `claude mcp add --transport http longbridge https://mcp.longbridge.com --header \"Authorization: Bearer {token}\"`. \
         Then reconnect / re-initialize the session and re-list tools to see the full set.",
        token = token.access_token,
    );

    let body = serde_json::json!({
        "status": "authenticated",
        "message": next_steps,
        "account_channel": account_channel,
        "scopes": scopes,
        "access_token": token.access_token,
        "refresh_token": token.refresh_token,
        "token_type": token.token_type.unwrap_or_else(|| "Bearer".into()),
        "expires_in": token.expires_in,
    });

    Ok(tool_result(body.to_string()))
}

async fn exchange_code(code: &str) -> Result<TokenResponse, McpError> {
    let url = format!("{}/oauth2/token", oauth_base_url());

    let client_id = agent_client_id();
    let form = [
        ("grant_type", "authorization_code"),
        ("code", code),
        ("redirect_uri", AGENT_REDIRECT_URI),
        ("client_id", client_id.as_str()),
    ];

    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(15))
        .user_agent(concat!("longbridge-mcp/", env!("CARGO_PKG_VERSION")))
        .build()
        .map_err(|e| McpError::internal_error(format!("failed to build http client: {e}"), None))?;

    let resp = client.post(&url).form(&form).send().await.map_err(|e| {
        McpError::internal_error(
            format!("failed to reach the Longbridge token endpoint: {e}"),
            None,
        )
    })?;

    let status = resp.status();
    let text = resp.text().await.map_err(|e| {
        McpError::internal_error(format!("failed to read token endpoint response: {e}"), None)
    })?;

    if !status.is_success() {
        // Surface a self-healing hint rather than a raw HTTP error so the AI can
        // guide the user to regenerate the code.
        let detail = serde_json::from_str::<TokenErrorResponse>(&text)
            .ok()
            .and_then(|e| e.error_description.or(e.error).filter(|s| !s.is_empty()))
            .unwrap_or_else(|| format!("token endpoint returned HTTP {status}"));
        return Err(McpError::invalid_params(
            format!("{} ({})", self_heal_hint(), detail),
            None,
        ));
    }

    serde_json::from_str::<TokenResponse>(&text).map_err(|e| {
        McpError::internal_error(
            format!("unexpected token endpoint response (could not parse): {e}"),
            None,
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // Shared vector with longbridge-terminal: the connect page displays
    // `RKBXES26iL0CdQL85vXz+tSNeoHeqyUuLEz3nVWgqVU=` as
    // `5ctXgj3mEtEHoUBRwJnyURf4EkfA1924fY3o9Njev2zp` (base58).
    const ORIGINAL: &str = "RKBXES26iL0CdQL85vXz+tSNeoHeqyUuLEz3nVWgqVU=";
    const BASE58_FORM: &str = "5ctXgj3mEtEHoUBRwJnyURf4EkfA1924fY3o9Njev2zp";
    const BASE64URL_FORM: &str = "RKBXES26iL0CdQL85vXz-tSNeoHeqyUuLEz3nVWgqVU";

    #[test]
    fn base58_display_form_decodes_to_original_code() {
        assert_eq!(auth_code_candidates(BASE58_FORM)[0], ORIGINAL);
    }

    #[test]
    fn legacy_base64url_form_and_raw_pass_through() {
        assert!(auth_code_candidates(BASE64URL_FORM).contains(&ORIGINAL.to_string()));
        assert!(auth_code_candidates(ORIGINAL).contains(&ORIGINAL.to_string()));
        assert!(auth_code_candidates("   ").is_empty());
    }

    #[tokio::test]
    async fn already_authenticated_short_circuits() {
        let result = authenticate(
            true,
            AuthenticateParam {
                auth_code: "anything".into(),
            },
        )
        .await
        .expect("already-authenticated path must succeed");
        let json = serde_json::to_string(&result.structured_content).unwrap();
        assert!(json.contains("already_authenticated"), "got: {json}");
    }

    #[tokio::test]
    async fn empty_code_is_rejected_with_hint() {
        let err = authenticate(
            false,
            AuthenticateParam {
                auth_code: "   ".into(),
            },
        )
        .await
        .expect_err("empty code must be rejected");
        assert!(
            err.message.contains(CONNECT_PAGE_URL),
            "got: {}",
            err.message
        );
    }

    #[tokio::test]
    async fn exchange_failure_includes_self_heal_hint() {
        // Point the exchange at a local server that returns an OAuth error body.
        use std::io::{Read, Write};
        use std::net::TcpListener;

        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let addr = listener.local_addr().unwrap();
        std::thread::spawn(move || {
            if let Ok((mut stream, _)) = listener.accept() {
                let mut buf = [0u8; 2048];
                let _ = stream.read(&mut buf);
                let body = r#"{"error":"invalid_grant","error_description":"code expired"}"#;
                let resp = format!(
                    "HTTP/1.1 400 Bad Request\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
                    body.len(),
                    body
                );
                let _ = stream.write_all(resp.as_bytes());
            }
        });

        // SAFETY: single-threaded test setup; no other thread reads this env var here.
        unsafe { std::env::set_var("LONGBRIDGE_HTTP_URL", format!("http://{addr}")) };

        let err = authenticate(
            false,
            AuthenticateParam {
                auth_code: "expired-code".into(),
            },
        )
        .await
        .expect_err("expired code must fail");

        unsafe { std::env::remove_var("LONGBRIDGE_HTTP_URL") };

        assert!(
            err.message.contains(CONNECT_PAGE_URL),
            "got: {}",
            err.message
        );
        assert!(err.message.contains("code expired"), "got: {}", err.message);
    }
}
